defaults:
  - algo: me
  - task: optim/arm
  - hydra: local
  - _self_

num_loops: 10
seed: 42
plots_dir: plots

corrected_metrics: 
  use: True
  evals: 128

wandb:
  project: QDax_bench
  entity: p-templier-imperial-college-london
  use: False
  tag: null

csv:
  use: True
  subsample: 10
plot: True