defaults:
  - algo: me
  - task: optim/arm
  - hydra: local
  - _self_

num_loops: 10
seed: 42

corrected_metrics: 
  use: True
  evals: 128

wandb:
  project: QDax_bench
  entity: p-templier-imperial-college-london
  use: False
  tag: null

log_csv: True
plot: True