plotting:
  algo_name: MAP-Elites

archive:
  num_init_cvt_samples: 5000
  num_centroids: 1024

# Factory
factory: 
  _target_: qdax_bench.factories.me.MEFactory

emitter: 
  _target_: qdax.core.emitters.standard_emitters.MixingEmitter
  # _partial_: true
  variation_fn: 
    _target_: qdax.core.emitters.mutation_operators.isoline_variation
    _partial_: true
    line_sigma: ${algo.params.line_sigma}
    iso_sigma: ${algo.params.iso_sigma}
  batch_size: ${algo.params.batch_size}
  variation_percentage: 1.0
  mutation_fn: null

group_defaults:
  kheperax:
    iso_sigma: 0.2
    line_sigma: 0.0
    batch_size: 64  
  brax:
    iso_sigma: 0.005
    line_sigma: 0.05
    batch_size: 1024

params: ${oc.select:algo.env_params.${task.env_name}, ${algo.group_defaults.kheperax}}

env_params:
  kheperax_pointmaze: ${algo.group_defaults.kheperax}
  kheperax_snake: ${algo.group_defaults.kheperax}
  kheperax_standard: ${algo.group_defaults.kheperax}
  halfcheetah_uni: ${algo.group_defaults.brax}
  walker2d_uni: ${algo.group_defaults.brax}
  antmaze: ${algo.group_defaults.brax}