defaults:
  - override launcher: joblib
  - _self_

job:
  chdir: True
run:
  dir: ./output/${now:%Y-%m-%d_%H%M%S_%f}
sweep:
  dir: ./output/${now:%Y-%m-%d_%H%M%S_%f}
  subdir: ${hydra.job.num}

launcher:
  n_jobs: 1

sweeper:
  params:
    task: debug, debug_brax
    algo: me, pga_me