defaults:
  - override launcher: hpc_launcher
  - _self_

job:
  chdir: True
run:
  dir: ./hpc/${now:%Y-%m-%d_%H%M%S_%f}
sweep:
  dir: ./hpc/${now:%Y-%m-%d_%H%M%S_%f}
  subdir: ${hydra.job.num}

launcher:
  replace_hydra: hpc_basic
  hpc: ptemplie@login.cx3.hpc.imperial.ac.uk
  email: p.templier@imperial.ac.uk
  job_name: QDaxBench
  walltime: 11:59:00
  nnodes: 1
  ncpus: 4
  mem: 16gb
  ngpus: 1
  gpu_type: L40S
  njobs: 1
  n_runs_per_job: 5
  add_seed: True
  container: latest
  run_jobs: false

# sweeper:
#   params:
#     task: kh_standard, kh_pointmaze, kh_snake
#     task.stochastic: true
#     algo: me

sweeper:
  params:
    task: halfcheetah, walker_2d
    task.stochastic: true, false
    algo: me, pga_me