brax:
  version: v1 # brax version: v1 or v2
  legacy_spring: false # For v1
  backend: spring # For v2

stochastic: false
episode_length: 1000
total_evaluations: 1e7

network:
  policy_hidden_layer_sizes: [256, 256]
  activation: tanh

es_params:
  sigma_init: 0.05
  popsize: 256
  es_type: LM_MA_ES

descriptors:
  minval: [0.0, 0.0]
  maxval: [1.0, 1.0]