config_origin: QDax_bench

setup_type: brax

brax:
  version: v2 # brax version: v1 or v2
  legacy_spring: false # For v1
  backend: spring # For v2

stochastic: false
episode_length: 1000
total_evaluations: 1e7

network:
  policy_hidden_layer_sizes: [256, 256, 256]
  activation: tanh

descriptors:
  minval: [0.0, 0.0]
  maxval: [1.0, 1.0]