defaults:
  - brax # Inherit all settings from brax
  - _self_ # Allow overriding inherited values

env_name: halfcheetah_uni

plotting:
  task_name: HalfCheetah ${task.brax.version}
  fitness_bounds: [-500, 7000]
  max_eval_cell: 6

total_evaluations: 5e6
