config_origin: QDax_bench

setup_type: kheperax

episode_length: 250
stochastic: false
total_evaluations: 2e6

network:
  policy_hidden_layer_sizes: [8]
  activation: relu

plotting:
  task_name: Kheperax Base
  fitness_bounds: [-350, -150]
  max_eval_cell: 5.5

descriptors:
  minval: [0.0, 0.0]
  maxval: [1.0, 1.0]