defaults:
  - kh_standard # Inherit all settings from standard.yaml
  - _self_ # Allow overriding inherited values

env_name: kheperax_pointmaze

total_evaluations: 1e6

plotting:
  task_name: Kheperax PointMaze
  fitness_bounds: [-400, -100]
  max_eval_cell: 5.5

descriptors:
  minval: [0.0, 0.0]
  maxval: [1.0, 1.0]