env_name: halfcheetah_uni

plotting:
  task_name: HalfCheetah
  fitness_bounds: [-500, 7000]
  max_eval_cell: 6

episode_length: 1000
stochastic: false
legacy_spring: false
total_evaluations: 5e6

network:
  policy_hidden_layer_sizes: [256, 256]
  activation: tanh

es_params:
  sigma_init: 0.05
  popsize: 256
  es_type: LM_MA_ES

descriptors:
  minval: [0.0, 0.0]
  maxval: [1.0, 1.0]