defaults:
  - jedi # Inherit all settings from jedi.yaml
  - _self_ # Allow overriding inherited values

restarter:
  _target_: qdax_es.utils.restart.DualConvergenceRestarter
  min_score_spread: ${algo.params.min_score_spread}
  min_bd_spread: ${algo.params.min_bd_spread}
  min_gens: ${algo.params.min_gens}
  max_gens: ${algo.params.max_gens}

plotting:
  algo_name: ${algo.gp.jedi_prefix}DyJEDi (x${algo.pool_size} | Î±=${algo.params.alpha}) Dy(S ${algo.params.min_score_spread} | D ${algo.params.min_bd_spread})

params:
  alpha: ${oc.select:algo.env_params.${task.env_name}.alpha, ${algo.default_params.alpha}}
  min_gens: ${oc.select:algo.env_params.${task.env_name}.min_gens, ${algo.default_params.min_gens}}
  max_gens: ${oc.select:algo.env_params.${task.env_name}.max_gens, ${algo.default_params.max_gens}}
  min_score_spread: ${oc.select:algo.env_params.${task.env_name}.min_score_spread, ${algo.default_params.min_score_spread}}
  min_bd_spread: ${oc.select:algo.env_params.${task.env_name}.min_bd_spread, ${algo.default_params.min_bd_spread}}

default_params:
  alpha: 0.5
  min_gens: 10
  max_gens: 500
  min_score_spread: 5
  min_bd_spread: 0.05

env_params:
  kheperax_pointmaze:
    alpha: 0.3
    min_score_spread: 10
    min_bd_spread: 0.1

  kheperax_snake:
    alpha: 0.3
    min_score_spread: 10
    min_bd_spread: 0.1

  kheperax_standard: 
    alpha: 0.7
    min_score_spread: 10
    min_bd_spread: 0.1

  halfcheetah_uni:
    alpha: 0.3
    max_gen: 1000
    min_score_spread: 10

  walker2d_uni:
    alpha: 0.3
    max_gen: 1000
    min_score_spread: 10

  antmaze:
    alpha: 0.3
    max_gen: 2000
    min_score_spread: 100


