defaults:
  - gp: gp 
  - _self_ 

# Plotting name
plotting:
  algo_name: ${algo.gp.jedi_prefix}JEDi (x${algo.pool_size} | Î±=${algo.params.alpha} | ${algo.params.gens} gens)

algo: jedi
pool_size: 4
global_norm: false

restarter:
  _target_: qdax_es.utils.restart.FixedGens
  max_gens: ${algo.params.gens}

gp:
  n_steps: 1000

archive:
  num_init_cvt_samples: 5000
  num_centroids: 1024

# Factory
factory: 
  _target_: qdax_es.factories.jedi.JEDiFactory

# Repertoire
repertoire_init: ${oc.select:algo.gp.repertoire_init, ${algo.default_repertoire_init}}

default_repertoire_init:
  _target_: qdax_es.core.containers.gp_repertoire.GPRepertoire.init
  _partial_: true
  weighted: false


# Algo parameters
params:
  alpha: ${oc.select:algo.env_params.${task.env_name}.alpha, ${algo.default_params.alpha}}
  gens: ${oc.select:algo.env_params.${task.env_name}.gens, ${algo.default_params.gens}}

default_params:
  alpha: 0.5
  gens: 100

env_params:
  kheperax_pointmaze:
    alpha: 0.3
  kheperax_snake:
    alpha: 0.3
  kheperax_standard:
    alpha: 0.7
  halfcheetah_uni:
    alpha: 0.5
    gens: 100
  walker2d_uni:
    alpha: 0.7
    gens: 1000
  antmaze:
    alpha: 0.3
    gens: 1000

