defaults:
  - default_qd # Inherit all settings from default_qd
  - _self_ # Allow overriding inherited values

config_origin: QDax_bench

plotting:
  algo_name: MAP-Elites

# Factory
factory: 
  _target_: qdax_bench.factories.me.MEFactory

emitter: 
  _target_: qdax.core.emitters.standard_emitters.MixingEmitter
  # _partial_: true
  variation_fn: 
    _target_: qdax.core.emitters.mutation_operators.isoline_variation
    _partial_: true
    line_sigma: ${algo.params.line_sigma}
    iso_sigma: ${algo.params.iso_sigma}
  batch_size: ${algo.params.batch_size}
  variation_percentage: 1.0
  mutation_fn: null

initial_batch: ${algo.params.batch_size}

group_defaults:
  kheperax:
    iso_sigma: 0.2
    line_sigma: 0.0
    batch_size: 64  
  brax:
    iso_sigma: 0.005
    line_sigma: 0.05
    batch_size: 1024
  optim:
    iso_sigma: 0.005
    line_sigma: 0.05
    batch_size: 4096
  bbob:
    iso_sigma: 0.005
    line_sigma: 0.05
    batch_size: 4096