defaults:
  - kh_base # Inherit all settings from standard.yaml
  - _self_ # Allow overriding inherited values

env_name: kheperax_snake

total_evaluations: 1e6

plotting:
  task_name: Kheperax Snake
  fitness_bounds: [-400, -100]
  max_eval_cell: 5.5
